{
 "title": "Hummingbird",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Hummingbird RESTFul API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(http_route) (rate(http_server_request_duration_seconds_count[$__rate_interval]) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Latency",
   "type": "timeseries",
   "description": "Hummingbird REST API traces.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "filters": [
      {
       "id": "4d8ded8e",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [ "hummingbird" ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Media Upload Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "media_upload_success_total{service_name=\"hummingbird\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Media Upload Failure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "media_upload_failure_total{service_name=\"hummingbird\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, max by(le) (rate(http_client_request_duration_seconds_bucket{service_name=\"hummingbird\"}[$__rate_interval]))) * 60",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.95, max by(le) (rate(http_client_request_duration_seconds_bucket{service_name=\"hummingbird\"}[$__rate_interval]))) * 60",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.75, max by(le) (rate(http_client_request_duration_seconds_bucket{service_name=\"hummingbird\"}[$__rate_interval]))) * 60",
     "legendFormat": "75th"
    },
    {
     "expr": "histogram_quantile(0.5, max by(le) (rate(http_client_request_duration_seconds_bucket{service_name=\"hummingbird\"}[$__rate_interval]))) * 60",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "RESTFul API Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"hummingbird\"} |= ``"
    }
   ]
  },
  {
   "title": "Hummingbird Asynchronous Workflows",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Successful Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum by(scope) (rate(media_async_process_success_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Lambda Invocations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 20 },
   "targets": [
    {
     "expr": "sum by(scope) (rate(media_async_process_failure_total[$__rate_interval])) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Process Media Lambda Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 20 },
   "targets": [
    {
     "filters": [
      {
       "id": "4d8ded8e",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "hummingbird-process-media-handler"
       ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Manage Media Lambda Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 20 },
   "targets": [
    {
     "filters": [
      {
       "id": "4d8ded8e",
       "operator": "=",
       "scope": "span",
       "value": []
      },
      {
       "id": "service-name",
       "operator": "=",
       "scope": "resource",
       "tag": "service.name",
       "value": [
        "hummingbird-manage-media-handler"
       ],
       "valueType": "string"
      }
     ],
     "limit": 100,
     "spss": 3,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Process Media Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"hummingbird-process-media-handler\"} |= ``"
    }
   ]
  },
  {
   "title": "Manage Media Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"hummingbird-manage-media-handler\"} |= ``"
    }
   ]
  }
 ]
}